# Generated by ariadne-codegen on 2023-11-19 01:06
# Source: graphql/queries.graphql

from typing import Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .film_query import FilmQuery


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def film_query(
        self, id: Union[Optional[str], UnsetType] = UNSET
    ) -> FilmQuery:
        query = gql(
            """
            query FilmQuery($id: ID) {
              film(id: $id) {
                title
                director
                releaseDate
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return FilmQuery.parse_obj(data)
