# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FilmQuery(BaseModel):
    film: Optional["FilmQueryFilm"]


class FilmQueryFilm(BaseModel):
    title: Optional[str]
    director: Optional[str]
    release_date: Optional[str] = Field(alias="releaseDate")


FilmQuery.model_rebuild()
FilmQueryFilm.model_rebuild()
