# Generated by ariadne-codegen on 2023-11-19 01:06
# Source: graphql/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FilmQuery(BaseModel):
    film: Optional["FilmQueryFilm"]


class FilmQueryFilm(BaseModel):
    title: Optional[str]
    director: Optional[str]
    release_date: Optional[str] = Field(alias="releaseDate")


FilmQuery.update_forward_refs()
FilmQueryFilm.update_forward_refs()
